### ISSUE TITLE
Add binary release

### ISSUE THREAD

**Issue by lmroz** [intelsdi-x/snap-plugin-collector-openfoam#10]
When readme is updated this plugin should have binary release there: https://github.com/intelsdi-x/snap-plugin-collector-openfoam/releases

**Comment by lmroz** [comment]
It also has no binary release there: http://snap.ci.snap-telemetry.io/plugins/snap-plugin-collector-openfoam/latest/linux/x86_64/snap-plugin-collector-openfoam (which is going to be used in example flow).

**Comment by nanliu** [comment]
This plugin has been updated with a release and the url link above is working as expected now.
